version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Jerusalem"
    open-pull-requests-limit: 10
    reviewers:
      - "bot-sync-up"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "type:infra"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "type:infra"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "type:infra"
