{{- if .Values.podDisruptionBudget.enabled }}
{{- range $name, $svc := dict "next" .Values.next "gateway" .Values.gateway "worker" .Values.worker }}
{{- if $svc.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $.Release.Name }}-{{ $name }}
spec:
  minAvailable: {{ $.Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $.Chart.Name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      component: {{ $name }}
{{- end }}
{{- end }}
{{- end }}
