global:
  env: staging
  domain: staging.example.com

next:
  replicaCount: 2
  autoscaling:
    minReplicas: 2
    maxReplicas: 4

gateway:
  replicaCount: 2
  autoscaling:
    minReplicas: 2
    maxReplicas: 4

worker:
  replicaCount: 2
  autoscaling:
    minReplicas: 2
    maxReplicas: 6

ingress:
  hosts:
    - host: staging.example.com
      paths:
        - { path: /,    pathType: Prefix, service: next }
        - { path: /api, pathType: Prefix, service: gateway }
  tls:
    - secretName: app-tls-staging
      hosts: [staging.example.com]
